// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiXwJyoNKejtV6czjI650c_0PMXFmypE',
    appId: '1:814412447092:web:a0027c6a15afd7140f0021',
    messagingSenderId: '814412447092',
    projectId: 'fleets-x9tytb',
    authDomain: 'fleets-x9tytb.firebaseapp.com',
    storageBucket: 'fleets-x9tytb.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCiXwJyoNKejtV6czjI650c_0PMXFmypE',
    appId: '1:814412447092:android:a0027c6a15afd7140f0021',
    messagingSenderId: '814412447092',
    projectId: 'fleets-x9tytb',
    storageBucket: 'fleets-x9tytb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCiXwJyoNKejtV6czjI650c_0PMXFmypE',
    appId: '1:814412447092:ios:a0027c6a15afd7140f0021',
    messagingSenderId: '814412447092',
    projectId: 'fleets-x9tytb',
    storageBucket: 'fleets-x9tytb.firebasestorage.app',
    iosBundleId: 'com.oilmanager.manager',
  );
}
